### ISSUE TITLE
SDRAM DIMMs not detected

### ISSUE THREAD

**Issue by sylvainpelissier** [groeck/i2c-tools#4]
After compiling i2c-tools from the git repository and after loading eeprom module, I got the following error:
_"Number of SDRAM DIMMs detected and decoded: 0"_
However, the RAM is detected by dmidecode tool.

**Comment by hrvoojex** [comment]
I also have this issue.

**Comment by srinidhiprabhu96** [comment]
http://www.richud.com/wiki/Ubuntu_See_Live_RAM_Timings_Decode_DIMMS

**Comment by hrvoojex** [comment]
Yes, I done that already. And when scaning I2C/SMBus I get:
```

Do you want to probe the I2C/SMBus adapters now? (YES/no): yes
Sorry, no supported PCI bus adapters found.
```
Mich41 on Arch forum says:
https://bbs.archlinux.org/viewtopic.php?id=168518

> 
Personally, I've never used decode-dimms with the eeprom driver. Once I know which bus is SMBus, I dump addresses 0x50-0x57 on this bus to files with i2cdump and run decode-dimms -x on them.

Could someone explain how to do this, step by step?

**Comment by groeck** [comment]
Please submit problems against i2c-tools to the i2c-tools mailing list at linux-i2c@vger.kernel.org. You might also want to test the latest version of i2c-tools, which is available from git://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git (the copy here was intended as a git clone of the SVN repository, which no longer exists, and is not guaranteed to be up to date).
