### ISSUE TITLE
C++ header guard

### ISSUE THREAD

**Issue by ryanbinns** [groeck/i2c-tools#9]
I suggest adding
```
#ifdef __cplusplus
extern "C" {
#endif
```
and
```
#ifdef __cplusplus
}
#endif
```
to the top and bottom of `smbus.h` so that the file can be included from C++ progams without causing linker issues.

**Comment by groeck** [comment]
Please submit problems against i2c-tools to the i2c-tools mailing list at linux-i2c@vger.kernel.org. You might also want to test the latest version of i2c-tools, which is available from git://git.kernel.org/pub/scm/utils/i2c-tools/i2c-tools.git (the copy here was intended as a git clone of the SVN repository, which no longer exists, and is not guaranteed to be up to date).
